# Lattice-backed Mackey functor data.
#
# This file defines a Mackey functor data type for a finite GAP group G.
# The key design choice is that the constructor immediately replaces all
# user-provided subgroup keys by the canonical subgroup objects appearing in
# GAP's subgroup lattice. This makes later comparisons and dictionary lookups
# more predictable, since most internal dictionaries use these lattice subgroup
# objects as keys.
#
# Values are finite abelian groups represented by their invariant factors:
#     [n1, n2, ..., nr]
# means Z/n1 x Z/n2 x ... x Z/nr, with n_i = 0 representing a free Z factor.
# A map between two such groups is represented by an integer matrix, and the
# helper functions from the abelian-group code check that the matrix descends
# to a well-defined homomorphism on the corresponding quotients.

# Return all subgroups of G as the actual GAP subgroup objects stored in
# GAP's subgroup lattice. These are the canonical subgroup objects used
# internally throughout this file.
function lattice_subgroups(G::GapObj)
    GAP.Globals.IsGroup(G) ||
        throw(ArgumentError("lattice_subgroups(G) can only be called when G is a group"))

    L = GAP.Globals.LatticeSubgroups(G)
    result = GapObj[]

    for cls in GAP.Globals.ConjugacyClassesSubgroups(L)
        for H in GAP.Globals.Elements(cls)
            push!(result, H)
        end
    end

    return result
end

# Given a subgroup H supplied by the user, find the unique equal subgroup in
# the canonical subgroup list. This lets users pass mathematically equal GAP
# subgroup objects while the internal data uses one fixed representative.
function canonical_subgroup(subgroups::Vector{GapObj}, H::GapObj)
    matches = [K for K in subgroups if K == H]

    length(matches) == 1 ||
        throw(ArgumentError("Subgroup key is not uniquely represented in the subgroup lattice"))

    return matches[1]
end

# Our convention is: is_subgroup_of(H, K) means H <= K.
# GAP.Globals.IsSubgroup(K, H) uses the parent group first, then the subgroup.
is_subgroup_of(H::GapObj, K::GapObj) = Bool(GAP.Globals.IsSubgroup(K, H))

function is_proper_subgroup(H::GapObj, K::GapObj)
    return H != K && is_subgroup_of(H, K)
end

# Compute the cover relations in the subgroup poset.
# A pair (H, K) is a cover if H < K and there is no subgroup L with H < L < K.
# The constructor asks the user for restriction and transfer maps only on these
# covers; maps for all comparable pairs are then generated by composition.
function cover_relations(subgroups::Vector{GapObj})
    covers = Tuple{GapObj,GapObj}[]

    for H in subgroups, K in subgroups
        is_proper_subgroup(H, K) || continue

        has_intermediate = any(
            L -> is_proper_subgroup(H, L) && is_proper_subgroup(L, K),
            subgroups,
        )

        has_intermediate || push!(covers, (H, K))
    end

    return covers
end

# Identity matrix on the abelian group represented by `value`.
# The length of `value` is the number of generators in the chosen presentation.
identity_map(value::Vector{Int64}) =
    [i == j ? 1 : 0 for i in 1:length(value), j in 1:length(value)]

# Find the actual stored key (A, B) in an IdDict-like dictionary.
# Since GAP objects are not normally hashable, this file uses IdDict and then
# searches manually when mathematical equality or mixed identity/equality is
# needed. The first coordinate is compared by identity and the second by GAP
# equality, matching how these keys are used below.
function gap_pair_key(dict, A::GapObj, B::GapObj)
    for key in keys(dict)
        key[1] === A && key[2] == B && return key
    end
    return nothing
end

# Find the actual stored key A in an IdDict-like dictionary, comparing by object
# identity. This is used after canonicalization, where keys should be the exact
# GAP subgroup objects from the subgroup lattice.
function gap_key(dict, A::GapObj)
    for key in keys(dict)
        key === A && return key
    end
    return nothing
end

# Retrieve a map indexed by (H, K). If H == K, return the identity map instead
# of requiring the identity map to be stored explicitly.
function get_map(dict, H::GapObj, K::GapObj, values)
    H == K && return identity_map(values[H])

    key = gap_pair_key(dict, H, K)
    key === nothing && throw(ArgumentError("Missing map for subgroup pair"))

    return dict[key]
end

# Insert a restriction or transfer map after checking that it is a well-defined
# homomorphism between the finite abelian groups represented by `source` and
# `target`. If a map for the same pair is already present, the new matrix must
# define the same abelian-group homomorphism as the existing one.
function checked_insert_map!(dict, H, K, M, source, target, message)
    defines_fg_abelian_map(source, target, M) ||
        throw(ArgumentError(message))

    key = gap_pair_key(dict, H, K)
    if key === nothing
        dict[(H, K)] = M
        return true
    end

    are_equal_abelian_group_homomorphisms(source, target, dict[key], M) ||
        throw(ArgumentError("Two input maps disagree after lattice canonicalization"))

    return false
end

# Test whether (H, K) is one of the subgroup-lattice cover relations.
function has_cover(covers, H, K)
    return any(pair -> pair[1] === H && pair[2] === K, covers)
end

# Convert the user-provided values dictionary to one indexed by canonical
# subgroup-lattice objects. This also verifies that every subgroup in the
# lattice has exactly one value.
function canonicalize_values(subgroups, values)
    canonical_values = IdDict{GapObj,Vector{Int64}}()

    for (H, value) in values
        GAP.Globals.IsGroup(H) ||
            throw(ArgumentError("Each key of values must be a GAP group"))

        K = canonical_subgroup(subgroups, H)

        all(x -> x >= 0 && x != 1, value) ||
            throw(ArgumentError("Value of Mackey functor needs nonnegative entries, none equal to 1"))

        gap_key(canonical_values, K) === nothing ||
            throw(ArgumentError("Duplicate value for a lattice subgroup"))

        canonical_values[K] = value
    end

    for H in subgroups
        gap_key(canonical_values, H) !== nothing ||
            throw(ArgumentError("Missing value for a subgroup in the subgroup lattice"))
    end

    return canonical_values
end

# Canonicalize user-provided restriction or transfer maps.
# The user is expected to provide maps only for cover relations (H, K) with
# H < K. For restrictions, the matrix is interpreted as M(K) -> M(H).
# For transfers, the matrix is interpreted as M(H) -> M(K).
function canonicalize_cover_maps(subgroups, covers, values, maps, kind::Symbol)
    result = IdDict{Tuple{GapObj,GapObj},Matrix{Int64}}()

    for ((H0, K0), M) in maps
        H = canonical_subgroup(subgroups, H0)
        K = canonical_subgroup(subgroups, K0)

        has_cover(covers, H, K) ||
            throw(ArgumentError("Input $(kind) map must be on a subgroup-lattice cover relation"))

        source = kind == :restriction ? values[K] : values[H]
        target = kind == :restriction ? values[H] : values[K]
        checked_insert_map!(result, H, K, M, source, target, "$(kind) map is not well-defined")
    end

    for (H, K) in covers
        gap_pair_key(result, H, K) !== nothing ||
            throw(ArgumentError("Missing $(kind) map for a subgroup-lattice cover relation"))
    end

    return result
end

# Close the restriction maps under composition.
# If H < K < L, then res_H^L should be res_H^K * res_K^L.
# This function repeatedly composes known maps until every comparable pair has
# a stored restriction map.
function close_restrictions!(restrictions, subgroups, values)
    changed = true

    while changed
        changed = false
        keys_now = collect(keys(restrictions))

        for key_HK in keys_now, key_KL in keys_now
            H, K = key_HK
            K0, L = key_KL
            K0 === K || continue

            composed = restrictions[key_HK] * restrictions[key_KL]
            changed |= checked_insert_map!(
                restrictions,
                H,
                L,
                composed,
                values[L],
                values[H],
                "Composed restriction is not well-defined",
            )
        end
    end

    for H in subgroups, K in subgroups
        is_proper_subgroup(H, K) || continue
        gap_pair_key(restrictions, H, K) !== nothing ||
            throw(ArgumentError("Restrictions do not determine every comparable subgroup pair"))
    end
end

# Close the transfer maps under composition.
# If H < K < L, then tr_H^L should be tr_K^L * tr_H^K.
# This is the transfer analogue of close_restrictions!.
function close_transfers!(transfers, subgroups, values)
    changed = true

    while changed
        changed = false
        keys_now = collect(keys(transfers))

        for key_HK in keys_now, key_KL in keys_now
            H, K = key_HK
            K0, L = key_KL
            K0 === K || continue

            composed = transfers[key_KL] * transfers[key_HK]
            changed |= checked_insert_map!(
                transfers,
                H,
                L,
                composed,
                values[H],
                values[L],
                "Composed transfer is not well-defined",
            )
        end
    end

    for H in subgroups, K in subgroups
        is_proper_subgroup(H, K) || continue
        gap_pair_key(transfers, H, K) !== nothing ||
            throw(ArgumentError("Transfers do not determine every comparable subgroup pair"))
    end
end

# Conjugate a subgroup using the convention needed for the stored conjugation
# maps. With this convention, conjugate_subgroup(H, g) is gHg^{-1}.
conjugate_subgroup(H::GapObj, g::GapObj) = H^(g^-1)

# Insert a conjugation map for H and g.
# The target subgroup is computed and then canonicalized inside the subgroup
# lattice. If a conjugation map for the same key is already present, the two
# matrices must define the same abelian-group homomorphism.
function checked_insert_conjugation!(conjugations, subgroups, values, H, g, M)
    K = canonical_subgroup(subgroups, conjugate_subgroup(H, g))

    defines_fg_abelian_map(values[H], values[K], M) ||
        throw(ArgumentError("Conjugation map is not well-defined"))

    key = gap_pair_key(conjugations, H, g)
    if key === nothing
        conjugations[(H, g)] = M
        return true
    end

    are_equal_abelian_group_homomorphisms(values[H], values[K], conjugations[key], M) ||
        throw(ArgumentError("Conjugation maps disagree after lattice canonicalization"))

    return false
end

# Canonicalize the user-provided conjugation maps and check that each group
# element appearing in a key really belongs to G.
function canonicalize_conjugations(subgroups, values, conjugations, G)
    result = IdDict{Tuple{GapObj,GapObj},Matrix{Int64}}()

    for ((H0, g), M) in conjugations
        Bool(GAP.Globals.IN(g, G)) ||
            throw(ArgumentError("Conjugation key has second entry not an element of G"))

        H = canonical_subgroup(subgroups, H0)
        checked_insert_conjugation!(result, subgroups, values, H, g, M)
    end

    return result
end

# Add identity conjugation maps for elements h in H.
# Such elements conjugate H to itself, so the induced map should be the identity.
function add_identity_conjugations!(conjugations, subgroups, values)
    for H in subgroups
        id = identity_map(values[H])

        for h in GAP.Globals.Elements(H)
            checked_insert_conjugation!(conjugations, subgroups, values, H, h, id)
        end
    end
end

# Require the user to provide conjugation maps for enough generators of G.
# Identity conjugations for elements already inside H are skipped, since those
# were inserted automatically by add_identity_conjugations!.
function require_generator_conjugations(conjugations, subgroups, G)
    for H in subgroups
        for g in GAP.Globals.GeneratorsOfGroup(G)
            Bool(GAP.Globals.IN(g, H)) && continue

            gap_pair_key(conjugations, H, g) !== nothing ||
                throw(ArgumentError("Missing conjugation map for a group generator"))
        end
    end
end

# Close conjugation maps under composition.
# If H --x--> K and K --y--> L are known, then H --yx--> L is determined by
# composing the corresponding matrices. This loop adds all such consequences
# and finally checks that every pair (H, g) has a conjugation map.
function close_conjugations!(conjugations, subgroups, values, G)
    changed = true

    while changed
        changed = false
        keys_now = collect(keys(conjugations))

        for key_Hx in keys_now, key_Ky in keys_now
            H, x = key_Hx
            K, y = key_Ky
            K === canonical_subgroup(subgroups, conjugate_subgroup(H, x)) || continue

            z = y * x
            composed = conjugations[key_Ky] * conjugations[key_Hx]
            changed |= checked_insert_conjugation!(conjugations, subgroups, values, H, z, composed)
        end
    end

    for H in subgroups, g in GAP.Globals.Elements(G)
        gap_pair_key(conjugations, H, g) !== nothing ||
            throw(ArgumentError("Conjugations do not determine every group element"))
    end
end

# GAP returns double-coset representatives together with their sizes; this
# helper keeps only the representatives.
function double_coset_representatives(H, J, K)
    return [entry[1] for entry in GAP.Globals.DoubleCosetRepsAndSizes(H, J, K)]
end

# Verify the Mackey double-coset formula for every triple J, K <= H.
# Both sides are matrices defining maps M(K) -> M(J), and equality is checked
# as equality of homomorphisms between the presented abelian groups.
function validate_mackey_formula(subgroups, values, restrictions, transfers, conjugations)
    for H in subgroups, J in subgroups, K in subgroups
        is_subgroup_of(J, H) || continue
        is_subgroup_of(K, H) || continue

        left = get_map(restrictions, J, H, values) * get_map(transfers, K, H, values)
        right = zeros(Int64, length(values[J]), length(values[K]))

        for x in double_coset_representatives(H, J, K)
            xKxinv = conjugate_subgroup(K, x)
            xinvJx = J^x

            A = canonical_subgroup(subgroups, GAP.Globals.Intersection(J, xKxinv))
            B = canonical_subgroup(subgroups, GAP.Globals.Intersection(xinvJx, K))

            right += get_map(transfers, A, J, values) *
                     get_map(conjugations, B, x, values) *
                     get_map(restrictions, B, K, values)
        end

        are_equal_abelian_group_homomorphisms(values[K], values[J], left, right) ||
            throw(ArgumentError("Mackey formula failed"))
    end
end

"""
    MackeyFunctor(G, values, restrictions, transfers, conjugations; coefficient_ring=ZZ)
    MackeyFunctor(coefficient_ring, G, values, restrictions, transfers, conjugations)

A lattice-backed Mackey functor for a finite GAP group `G`.

The `values` dictionary assigns each subgroup a finitely generated abelian
group, represented by invariant factors. The `restrictions` and `transfers`
dictionaries provide matrices for subgroup-lattice cover relations `(H, K)`
with `H < K`; the constructor closes these maps under composition. The
`conjugations` dictionary provides conjugation maps indexed by `(H, g)`.

All subgroup keys are canonicalized to the subgroup objects stored in GAP's
subgroup lattice, and construction validates the Mackey double-coset formula.
"""
struct MackeyFunctor
    G::GapObj
    coefficient_ring::Ring
    lattice::GapObj
    subgroups::Vector{GapObj}
    covers::Vector{Tuple{GapObj,GapObj}}
    values::IdDict{GapObj,Vector{Int64}}
    restrictions::IdDict{Tuple{GapObj,GapObj},Matrix{Int64}}
    transfers::IdDict{Tuple{GapObj,GapObj},Matrix{Int64}}
    conjugations::IdDict{Tuple{GapObj,GapObj},Matrix{Int64}}

    function MackeyFunctor(
        coefficient_ring,
        G::GapObj,
        values::IdDict{GapObj,Vector{Int64}},
        restrictions::IdDict{Tuple{GapObj,GapObj},Matrix{Int64}},
        transfers::IdDict{Tuple{GapObj,GapObj},Matrix{Int64}},
        conjugations::IdDict{Tuple{GapObj,GapObj},Matrix{Int64}},
    )
        # Basic input validation.
        coefficient_ring isa Ring ||
            throw(ArgumentError("Coefficient ring must be an AbstractAlgebra commutative ring"))

        GAP.Globals.IsGroup(G) ||
            throw(ArgumentError("First entry G must be a GAP group"))

        # Build the subgroup lattice and its cover relations.
        lattice = GAP.Globals.LatticeSubgroups(G)
        subs = lattice_subgroups(G)
        covers = cover_relations(subs)

        # Replace user-provided subgroup keys by canonical lattice subgroup keys.
        canonical_values = canonicalize_values(subs, values)
        canonical_restrictions =
            canonicalize_cover_maps(subs, covers, canonical_values, restrictions, :restriction)
        canonical_transfers =
            canonicalize_cover_maps(subs, covers, canonical_values, transfers, :transfer)
        canonical_conjugations =
            canonicalize_conjugations(subs, canonical_values, conjugations, G)

        # Generate all comparable-pair restriction and transfer maps by composing
        # the user-provided cover-relation maps.
        close_restrictions!(canonical_restrictions, subs, canonical_values)
        close_transfers!(canonical_transfers, subs, canonical_values)

        # Add and close conjugation maps until maps for every pair (H, g) are known.
        add_identity_conjugations!(canonical_conjugations, subs, canonical_values)
        require_generator_conjugations(canonical_conjugations, subs, G)
        close_conjugations!(canonical_conjugations, subs, canonical_values, G)

        # Finally, check the Mackey double-coset formula.
        validate_mackey_formula(
            subs,
            canonical_values,
            canonical_restrictions,
            canonical_transfers,
            canonical_conjugations,
        )

        # Store only canonicalized and fully closed data.
        return new(
            G,
            coefficient_ring,
            lattice,
            subs,
            covers,
            canonical_values,
            canonical_restrictions,
            canonical_transfers,
            canonical_conjugations,
        )
    end
end

# Convenience outer constructor. Defaults the coefficient ring to ZZ and then
# delegates to the main inner constructor above.
function MackeyFunctor(
    G::GapObj,
    values::IdDict{GapObj,Vector{Int64}},
    restrictions::IdDict{Tuple{GapObj,GapObj},Matrix{Int64}},
    transfers::IdDict{Tuple{GapObj,GapObj},Matrix{Int64}},
    conjugations::IdDict{Tuple{GapObj,GapObj},Matrix{Int64}};
    coefficient_ring=ZZ,
)
    return MackeyFunctor(
        coefficient_ring,
        G,
        values,
        restrictions,
        transfers,
        conjugations,
    )
end
